<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'&& $_SESSION['userRole'] !== 'Agent'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<style>
    input:focus:required:invalid {border: 1px solid red;}
    input:required:valid { border: 1px solid #d9dee3; }
    select:focus:required:invalid {border: 1px solid red;}
    select:required:valid { border: 1px solid #d9dee3; }
    textarea:focus:required:invalid {border: 1px solid red;}
    textarea:required:valid { border: 1px solid #d9dee3; }
</style>
<!-- / Navbar -->

      <!-- Content wrapper -->
      <div class="content-wrapper">
        <!-- Content -->
          <div class="container-xxl flex-grow-1 container-p-y">
            
                  
          <h4 class="fw-bold py-3 mb-4">
            <span class="text-muted fw-light">Vehicles /</span> models
          </h4>

          <!-- Basic Bootstrap Table -->
          <div class="card">
            <div class="flexDiv">
              <h5 class="card-header">toutes les models</h5>
              <!-- Button trigger modal -->
              <form id="searchDriverForm" autocomplete="off">
                <div class="d-flex g-3">
                    <input name="searchmodel" class="form-control form-control-sm me-2" type="search" placeholder="Recherche un model">
                    <button type="submit" disabled="true" id="searchmodelBtn" class="btn btn-primary btn-sm">Rechercher</button>
                </div>
              </form>
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalScrollable">
                Ajouter Models
              </button>
            </div>
           
            <span class="ms-3" id="deleteErr"></span>
            <div class="table-responsive text-nowrap">
              <table class="table">
                <thead>
                  <tr>
                    <th>Model</th>
                    <th>Type de vehicule</th>
                    <th>puissance moteur</th>
                    <th>puissance Administrative</th>
                    <th>boite vitesse</th>
                    <th>reservoir</th>
                    <th>nombre de place</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody class="table-border-bottom-0"></tbody>
              </table>
              
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <div class="demo-inline-spacing">
                    <!-- Basic Pagination -->
                    <nav aria-label="Page navigation">
                      <ul class="pagination"></ul>
                    </nav>
                    <!--/ Basic Pagination -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--/ Basic Bootstrap Table -->
          <div class="modal fade" id="modalScrollable2" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalScrollableTitle">models Details</h5>
                </div>
                <div class="modal-body" id="detailsBody">
                  <div class="text-center fs-3">
                  
                    <i class='bx bx-loader-alt bx-spin fs-1'></i>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" id="closeDetails" data-bs-dismiss="modal">Fermer</button>
                </div>
              </div>
            </div>
          </div>
          <hr class="my-5">
                    
      </div>
<!-- / Content -->
 <!-- Default Modal -->
 <div class="col-lg-8 col-md-8">
  <form id="modelForm">
  <div class="modal fade " id="modalScrollable" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog  modal-lg modal-dialog-scrollable" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalScrollableTitle">Nouvelle models</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <!-- <form id="vehicleForm" autocomplete="off"> -->
          <span class="ms-4 p-1" id="errDiv"></span>
        <div class="modal-body">        
          <div class="row">
            <div class="col mb-3">
              <label for="model" class="form-label">Model</label>
              <input name="model" type="text" id="model" class="form-control" placeholder="" required>
            </div>
          </div>
          <div class="row">
              <div class="col mb-3" id="selectParent">
                <label for="defaultSelectRole" class="form-label">Type de vehicle</label>
                <select id="typev" name="typev" class="form-select" required>
                  <option value="">select</option>
                 
                 </select>
                 </div>
                 </div>
          <div class="row">
            <div class="col mb-3">
              <label for="place" class="form-label">Nombre de place </label>
              <input name="place" type="number" id="place" class="form-control" placeholder="" required>
            </div>
          </div>
          <div class="row">
            <div class="col mb-3">
              <label for="puissanceM" class="form-label">Puissance de moteur</label>
              <input name="puissanceM" type="number" id="puissanceM" class="form-control" placeholder="" required>  
          </div>
            </div>
            <div class="row">
            <div class="col mb-3">
              <label for="puissanceA" class="form-label">Puissance de Administrative</label>
              <input name="puissanceA" type="number" id="puissanceA" class="form-control" placeholder="" required>  
          </div>
            </div>
            <div class="row">
            <div class="col mb-3">
              <label for="bvitesse" class="form-label">Boite de voitesse</label>
              <input name="bvitesse" type="number" id="bvitesse" class="form-control" placeholder="" required>  
          </div>
            </div>
            <div class="row">
            <div class="col mb-3">
              <label for="reservoir" class="form-label">Réservoir</label>
              <input name="reservoir" type="number" id="reservoir" class="form-control" placeholder="" required>  
          </div>
            </div>
            <div class="row">
              <div class="col mb-3" id="selectParent">
                <label for="typec" class="form-label">Type de carburant</label>
                <select id="typec" name="typec" class="form-select" required>
                <option value="" selected></option>
                     <option value="Essance">Essance</option>
                     <option value="Mazout">Mazout</option>
                     <option value="Electrique">Electrique</option>
                     <option value="Hybrid">Hybrid</option>
                </select>
              </div>
            </div>
           

        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Fermer</button>
          <button type="submit" class="btn btn-primary">Ajouter Vehicle</button>
        </div>
      </div>
    </div>
  </div>
</form>
</div>




<!-- Footer -->
<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
      <div class="content-backdrop fade"></div>
    </div>
    <!-- Content wrapper -->
  </div>
  <!-- / Layout page -->
</div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <script src="/views/assets/js/pages-account-settings-account.js"></script>
  <script src="/views/api/modulevehicle.API.js"></script>

  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>

  <!-- Page JS -->
  
</body>


</html>
