<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'&&$_SESSION['userRole'] !== 'chauffeur'&& $_SESSION['userRole'] !== 'Agent'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
      <!-- Content wrapper -->
      <div class="content-wrapper">
        <!-- Content -->



       
          <div class="container-xxl flex-grow-1 container-p-y">
          <div class="col-md-12">
   
    <div class="card mb-4">
    

          <!-- Basic Bootstrap Table -->
          <div class="card-body">
          <ul class="nav nav-pills flex-column flex-md-row mb-3">
    <li class="nav-item"><a class="nav-link active " href="/ordres"> Toutes les ordres</a>

  </li>
      <li class="nav-item"><a class="nav-link " href="/mission"> Nouvelle Mission</a></li>
      <li class="nav-item"><a class="nav-link " href="/ordre">Nouvelle Excursion/Transferet</a></li>
    </ul>     
          <h4 class="fw-bold py-3 mb-4" id="ssllaal">
            <span class="text-muted fw-light">Ordres/</span> historiques
          </h4>
            <div class="flexDiv">
              
              <h5 class="card-header">Tous les Ordres</h5>
              <!-- Button trigger modal -->
             
            </div>
            <span class="ms-3" id="deleteErr"></span>
            <div class="table-responsive text-nowrap">
              <table class="table">
                <thead>
                  <tr>
                    <th>ticket</th>

                    <th>depart</th>
                    <th>hotel</th>
                    <th>chambre</th>
                    <th>client</th>
                    <th>num enf</th>
                    <th>num adl</th>
                    <th>num bebe</th>
                    
                    <th>action</th>
                    
                  </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                  
                    <?php 
                    $currentarray = $tickets;



                    if($ordre['data']['ligne']==='direct')
                    
                    {for ($i = 0; $i < count($currentarray) - 1; $i++) {
                        $minIndex = $i;
                        for ($j = $i + 1; $j < count($currentarray); $j++) {
                                if($currentarray[$j]['zone'] >$currentarray[$minIndex]['zone']){
                                    $minIndex=$minIndex;
                                }
                                if($currentarray[$j]['zone'] === $currentarray[$minIndex]['zone']){
                                    if ($currentarray[$j]['numero'] < $currentarray[$minIndex]['numero']) {
                                        $minIndex = $j; 
                                    }
                                }
                          
                        }
                        if ($minIndex !== $i) {
                            $tmp = $currentarray[$i];
                            $currentarray[$i] = $currentarray[$minIndex];
                            $currentarray[$minIndex] = $tmp;
                        }
                    }}
                    else{for ($i = 0; $i < count($currentarray) - 1; $i++) {
                        $maxIndex = $i;
                        for ($j = $i + 1; $j < count($currentarray); $j++) {
                            if ($currentarray[$j]['zone'] > $currentarray[$maxIndex]['zone']) {
                                $maxIndex = $j; 
                            } elseif ($currentarray[$j]['zone'] === $currentarray[$maxIndex]['zone']) {
                                
                                if ($currentarray[$j]['numero'] > $currentarray[$maxIndex]['numero']) {
                                    $maxIndex = $j; 
                                }
                            }
                        }
                        if ($maxIndex !== $i) {
                            
                            $tmp = $currentarray[$i];
                            $currentarray[$i] = $currentarray[$maxIndex];
                            $currentarray[$maxIndex] = $tmp;
                        }
                    }
                    
                    }
                    
                    
                    
                    foreach($tickets as $ticket) : ?>
                      <tr>  
<td><?php echo $ticket['numero']?></td>
<td><?php echo $ticket['depart']?></td>

<td><?php echo $ticket['hotel']?></td>
<td><?php echo $ticket['chambre']?></td>
<td><?php echo $ticket['client']?></td>
<td><?php echo $ticket['adulte']?></td>
<td><?php echo $ticket['enfant']?></td>
<td><?php echo $ticket['bebe']?></td>
<td> 
                    <a href="ordres/<?php echo $ticket['id']?>" class="btn btn-outline-secondary"><i class="bx bx-edit"></i></a>
                    <button id="ordreShowBtn" data-tid="<?php echo $ticket['id']?>" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#modalScrollable2"><i class="bx bx-show"></i></button>
                    <button id="ordreDeleteBtn" data-tid="<?php echo $ticket['id']?>" class="btn btn-danger"><i class="bx bx-trash "></i></button>
</td>


                    </tr>




                        <?php endforeach ?>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>

<td>total pax </td><td><?php
$total = 0; // Initialize $total outside the foreach loop
$totalb = 0;
$totals =0;
$totalt = 0;
foreach($tickets as $ticket) {
    $total += $ticket['adulte']; // Accumulate the total
}

echo $total; // Output the total
?></td>
<td><?php 
foreach($tickets as $ticket) {
  $totals += $ticket['enfant']; // Accumulate the total
}
echo $totals;
?></td>
<td>
<?php 
foreach($tickets as $ticket) {
  $totalb += $ticket['bebe']; // Accumulate the total
}
echo $totalb;
?>




</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>

<td>total general</td>
<td>
  

<?php 
foreach($tickets as $ticket) {
  $totalt += $ticket['bebe'] + $ticket['adulte'] + $ticket['enfant']; // Accumulate the total
}
echo $totalt;
?>



</td>
</tr>


                </tbody>
              </table>
              
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <div class="demo-inline-spacing">
                    <!-- Basic Pagination -->
                    <nav aria-label="Page navigation">
                      <ul class="pagination">
                       
                      </ul>
                    </nav>
                    <!--/ Basic Pagination -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--/ Basic Bootstrap Table -->
          <div class="modal fade" id="modalScrollable2" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalScrollableTitle">Ordre de mission Details</h5>
                </div>
                <div class="modal-body" id="detailsBody">
                  <div class="text-center fs-3">
                    <i class='bx bx-loader-alt bx-spin fs-1'></i>
                  </div>
                </div>
                <div class="modal-footer">
                <!--a href="" class="btn btn-outline-secondary" id="printButton">Imprimer</a!-->
                  <button type="button" class="btn btn-outline-secondary" id="closeDetails" data-bs-dismiss="modal">Fermer</button>
                </div>
              </div>
            </div>
          </div>
          <hr class="my-5">
                    
      </div>
      
      
<!-- / Content -->
<!-- Footer -->
  <?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
      <div class="content-backdrop fade"></div>
    </div>
    <!-- Content wrapper -->
  </div>
  <!-- / Layout page -->
</div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->
  
  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <script src="/views/assets/js/pages-account-settings-account.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>
  <script src="/views/api/tickets.API.js"></script>

  <!-- Page JS -->
  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/tables-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:32 GMT -->
</html>
