<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'&& $_SESSION['userRole'] !== 'chauffeur'&& $_SESSION['userRole'] !== 'Agent'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<style>
    input:focus:required:invalid {border: 1px solid red;}
    input:required:valid { border: 1px solid #d9dee3; }
    select:focus:required:invalid {border: 1px solid red;}
    select:required:valid { border: 1px solid #d9dee3; }
    textarea:focus:required:invalid {border: 1px solid red;}
    textarea:required:valid { border: 1px solid #d9dee3; }
</style>
<link rel="stylesheet" href="/views/assets/css/selectize.css"/>
      

      <!-- Content wrapper -->
      <div class="content-wrapper">

        <!-- Content -->
        
          <div class="container-xxl flex-grow-1 container-p-y">
            
            
<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Carburant/</span> Ajouter</h4>

<!-- Basic Layout -->
<div class="row">
  <div class="col-xl">
    <div class="card mb-4">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Ajouter Carburant a Vehicule</h5>
      </div>
      <div class="card-body">
        <span id="addcarburanterr"></span>
        <form autocomplete="off" id="editcarburant">
       
        <div class="row">
      <div class="mb-3">
            <label class="form-label" for="select_box2">Excursion</label>
                <select class="form-control"  id="select_box" aria-label="Default select example" required>
                <option value="<?php echo $carburant['data']['excursionUuid'];?>" selected><?php echo $carburant['data']['nom'];?></option>
                </select>
          </div>
      </div>

      <div class="row">
      <div class="mb-3">
            <label class="form-label" for="select_box">VehicUle</label>
                <select class="form-control" id="select_box2" aria-label="Default select example" required>
                    <option value="<?php echo $carburant['data']['vehicleUuid'];?>" selected><?php echo $carburant['data']['regisNumber'];?> </option>
                </select>
          </div>
      </div>
      <div class="mb-3">
            <label class="form-label" for="select_box">chauffeur</label>
                <select class="form-control" id="select_box3" aria-label="Default select example" required>
                    <option selected value="<?php echo $carburant['data']['driverUuid'];?>" id=""><?php echo $carburant['data']['driverFullName'];?></option>
                </select>
               </div>
               <div class="row">
            <div class="col mb-3"> 
              <label for="color" class="form-label">date excursion</label>
              <input type="date" name="date" id="excursion"value="<?php echo $carburant['data']['date'];?>" name="excursion"class="form-control" placeholder=""  value="<?php echo date('Y-m-d'); ?>">
            </div>
          </div> 
       
          <div class="row">
          <div class="mb-3">
            <label class="form-label" for="basic-default-fullname">type de carburant</label>
               <select name="type" value="<?php echo $carburant['data']['type'];?>" id="" class="form-control">
                      <option value="essance">essance</option>
                        <option value="gasoil">gasoil</option>
                </select>
                </div>
      
          </div>
          <div class="row">
          <div class="mb-3">
            <label class="form-label" for="basic-default-fullname">Quantité en L</label>
            <input name="quantite" id="quantite" value="<?php echo $carburant['data']['quantite'];?>" step="0.01" type="number" class="form-control" oninput="this.setCustomValidity('')" id="basic-default-fullname" placeholder="" required/>
          </div>
          
          </div>
          <div class="row">
          <div class="mb-3">
            <label class="form-label" for="basic-default-fullname">Prix en dinar </label>
            <input name="prix" id="prix" value="<?php echo $carburant['data']['prix'];?>" type="number" step="0.01" class="form-control" oninput="this.setCustomValidity('')" id="basic-default-fullname" placeholder="" required/>
          </div>
      
          </div>
          <div class="row">
          <div class="mb-3">
            <label class="form-label" for="basic-default-fullname">Obeservation</label>
            <input name="obeservation" id="obeservation" value="<?php echo $carburant['data']['obeservation'];?>" type="text" class="form-control" oninput="this.setCustomValidity('')" id="basic-default-fullname" placeholder="" required/>
          </div>
          </div>
          <button type="submit" class="btn btn-primary">Modifier</button>
        </form>
      </div>
    </div>
  </div>
 
</div>

            
          </div>
          <!-- / Content -->

          
          

<!-- Footer -->
  <?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  

  



  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>
    <script src="/views/api/carburants.API.js"></script>
  <script src="/views/dselect.js"></script>

  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/form-layouts-vertical.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:29 GMT -->
</html>
