<?php
  if(isset($_SESSION['userUuid'], $_SESSION['userEmail'], $_SESSION['userRole']) && isset($_COOKIE['userUuid'])){
    $_SESSION['curUrl'] = $_SERVER['PHP_SELF'];
    $pageArray = explode('/', $_SERVER['PHP_SELF']);
    $pageName = str_replace('-', ' ', str_replace('/', '',$_SERVER['PHP_SELF']));
    if(count($pageArray) > 2){
      $pageName2 = 'Edit '.ucwords($pageArray[1]);
    }else{
      $pageName2 = strlen($pageName) < 1 ? 'Dashboard' : ucwords($pageName);
    }
    $loggedInUser = LoginUser::getLoginUser();
    if($loggedInUser['userDefaultPass'] === 'yes'){
      include  $_SERVER['DOCUMENT_ROOT'].'/views/Authentication/forgottenPassword.phtml';
      exit();
    }

  }else{
    $_SESSION['prevUrl'] = $_SERVER['PHP_SELF'];
    header('Location: /login');
    die();
  }
?>

<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed " dir="ltr" data-theme="theme-default" data-assets-path="/views/assets/" data-template="vertical-menu-template-free">
<head>
    <meta charset=" UTF-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title><?php echo $pageName2 ?> - <?php echo isset(Settings::$getSiteName) ? Settings::$getSiteName : '';?></title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="/uploads/logos/<?php echo isset(Settings::$getLogo) ? Settings::$getLogo : ''?>" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&amp;display=swap" rel="stylesheet">

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="/views/assets/vendor/fonts/boxicons.css" />
    
    

    <!-- Core CSS -->
    <link rel="stylesheet" href="/views/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="/views/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="/views/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    
    <link rel="stylesheet" href="/views/assets/vendor/libs/apex-charts/apex-charts.css" />

    <!-- Page CSS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- Helpers -->
    <script src="/views/assets/vendor/js/helpers.js"></script>
    <link rel="stylesheet" href="/views/assets/css/datepicker.css">
                                                                                                                                                                    
    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="/views/assets/js/config.js"></script>
</head>

<body>

  <!-- Layout wrapper -->
<div class="layout-wrapper layout-content-navbar  ">
  <div class="layout-container">

<!-- Menu -->

<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">

  <div class="app-brand demo ">
    <a href="/" class="app-brand-link">
      <img width="180" height="60" src="/uploads/logos/<?php echo isset(Settings::$getLogo) ? Settings::$getLogo : ''?>" alt="">
    </a>

    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
      <i class="bx bx-chevron-left bx-sm align-middle"></i>
    </a>
  </div>

  <div class="menu-inner-shadow"></div>


  <ul class="menu-inner py-1">
  </br> 
</br> 
    <!-- Dashboard -->
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/' ? 'active open' : ''?>">
      <a href="/" class="menu-link">
        <i class="menu-icon tf-icons bx bx-home-circle"></i>


<div data-i18n="Dashboard">Dashboard</div>
      </a>
    </li>

    <?php if($_SESSION['userRole'] === 'admin' || $_SESSION['userRole'] === 'superAdmin'): ?>
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/workers' ||  $_SERVER['PHP_SELF'] === '/drivers' ? 'active open' : ''?>">
      <a href="javascript:void(0);" class="menu-link menu-toggle">
        <i class="menu-icon tf-icons bx bx-user"></i>
        <div data-i18n="Account Settings">Utilisateurs</div>
      </a>
      <ul class="menu-sub">
        <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/workers' ? 'active open' : ''?>">
          <a href="/workers" class="menu-link">
            <div data-i18n="Workers">Employes</div>
          </a>
        </li>
        <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/drivers' ? 'active open' : ''?>">
          <a href="/drivers" class="menu-link">
            <div data-i18n="Drivers">Chauffeurs</div>
          </a>
        </li>
        
      </ul>
    </li>
    <?php endif ?>
    <?php if($_SESSION['userRole'] === 'admin' || $_SESSION['userRole'] === 'superAdmin'||$_SESSION['userRole']==='Agent'): ?>
    <!-- Components -->
    <li class="menu-header small text-uppercase"><span class="menu-header-text"></span></li>

    <li class="menu-item  <?php echo $_SERVER['PHP_SELF'] === '/vehicles' || $_SERVER['PHP_SELF'] === '/typevehicle' ||$_SERVER['PHP_SELF'] === '/modelsvehicle'  ? 'active open' : ''?>">
      <a href="javascript:void(0);" class="menu-link menu-toggle">
        <i class="menu-icon tf-icons bx bx-bus"></i>
        <div data-i18n="Vehicles">Vehicles</div>
      </a>
      <ul class="menu-sub">
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/vehicles' ? 'active open' : ''?>">
    <a href="/vehicles" class="menu-link">
        <div data-i18n="vehicles">toutes les vehicules</div>
      </a>
    </li>
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/modelsvehicle' ? 'active open' : ''?>">
      <a href="/modelsvehicle" class="menu-link">
        <div data-i18n="modelsvehicle">models des vehicules</div>
      </a>
    </li>
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/typevehicle' ? 'active open' : ''?>">
      <a href="/typevehicle" class="menu-link">
        <div data-i18n="typevehicle">types des vehicules</div>
      </a>
    </li>
    </ul>


    </li>
    <li class="menu-item  <?php echo $_SERVER['PHP_SELF'] === '/excursion' || $_SERVER['PHP_SELF'] === '/tarifsexcursion'  ? 'active open' : ''?>">
    <a href="javascript:void(0);" class="menu-link menu-toggle">
    <i class="menu-icon tf-icons bx bx-trip"></i>
        <div data-i18n="Excursion">Missions</div>
    </a> 
    <ul class="menu-sub">
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/excursion' ? 'active open' : ''?>">
    <a href="/excursion" class="menu-link">
        <div data-i18n="Excursion">Missions</div>
      </a>
    </li>
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/tarifsexcursion' ? 'active open' : ''?>">
      <a href="/tarifsexcursion" class="menu-link">
        <div data-i18n="tarifsexcursion">tarifs</div>
      </a>
    </li>
    </ul>
    </li>
    <li class="menu-item  <?php echo $_SERVER['PHP_SELF'] === '/hotels' ? 'active' : ''?>">
      <a href="/hotels" class="menu-link">
        <i class="menu-icon tf-icons bx bx-hotel"></i>
        <div data-i18n="hotels">Hotels</div>
      </a>
    </li>


    <li class="menu-item  <?php echo $_SERVER['PHP_SELF'] === '/statistiques' ? 'active' : ''?>">
    <a href="javascript:void(0);" class="menu-link menu-toggle">
        <i class="menu-icon tf-icons bx bx-stats"></i>
        <div data-i18n="statistiques">statistiques</div>
      </a>
      <ul class="menu-sub">
        <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/statistiques/vehicles' ? 'active open' : ''?>">
          <a href="/statistiques/vehicles" class="menu-link">
            <div data-i18n="vehicles">vehicles</div>
          </a>
        </li>
        <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/statistiques/ordres' ? 'active open' : ''?>">
          <a href="/statistiques/ordres" class="menu-link">
            <div data-i18n="ordres">ordres</div>
          </a>
        </li>
        <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/statistiques/chauffeurs' ? 'active open' : ''?>">
          <a href="/statistiques/chauffeurs" class="menu-link">
            <div data-i18n="chauffeurs">chauffeurs</div>
          </a>
        </li>
        <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/statistiques/excursions' ? 'active open' : ''?>">
          <a href="/statistiques/excursions" class="menu-link">
            <div data-i18n="excursions">excursions</div>
          </a>
        </li>
        
      </ul>
    </li>
    <?php endif ?>

    <?php if($_SESSION['userRole'] === 'chauffeur' ): ?>
    <li class="menu-header small text-uppercase"><span class="menu-header-text"></span></li>
   <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/kilometerge' ||  $_SERVER['PHP_SELF'] === '/add-km' ? 'active open' : ''?>">
      <a href="javascript:void(0);" class="menu-link menu-toggle">
        <i class="menu-icon tf-icons bx bx-traffic-cone"></i>
        <div data-i18n="Form Layouts">kilometerage</div>
      </a>
      <ul class="menu-sub">
       
        <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/kilometerges' ? 'active open' : ''?>">
          <a href="/kilometerges" class="menu-link">
            <div data-i18n="All Sales">All kilometerage</div>
          </a>
        </li>
        
    </ul>
     <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/ordres' ||  $_SERVER['PHP_SELF'] === '/ordres' ? 'active open' : ''?>">
      <a href="/ordres" class="menu-link ">
        <i class="menu-icon tf-icons bx bx-task"></i>
        <div data-i18n="Form Layouts">Ordre de mission</div>
      </a>
    </li>
    <?php endif ?>
  <?php if($_SESSION['userRole'] === 'admin' || $_SESSION['userRole'] === 'superAdmin'||$_SESSION['userRole']==='Agent'): ?>
    <li class="menu-header small text-uppercase"><span class="menu-header-text"></span></li>
    


<li class="menu-item  <?php echo $_SERVER['PHP_SELF'] === '/historiquesmaintenance' || $_SERVER['PHP_SELF'] === '/listevehiculesmaintenance'  ? 'active open' : ''?>">
  <a href="javascript:void(0);" class="menu-link menu-toggle">
    <i class="menu-icon tf-icons bx bx-wrench"></i>
    <div data-i18n="Vehicles">Maintenance</div>
  </a>
  <ul class="menu-sub">
<li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/historiquesmaintenance' ? 'active open' : ''?>">
<a href="/historiquesmaintenance" class="menu-link">
    <div data-i18n="historiquesmaintenance">Historiques</div>
  </a>
</li>
<li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/listevehiculesmaintenance' ? 'active open' : ''?>">
  <a href="/listevehiculesmaintenance" class="menu-link">
    <div data-i18n="listevehiculesmaintenance">vehicules</div>
  </a>
</li>

</ul>


</li>
    <!-- Misc -->
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/carburants' ||  $_SERVER['PHP_SELF'] === '/carburants' ? 'active open' : ''?>">
      <a href="/carburants" class="menu-link ">
        <i class="menu-icon tf-icons bx bx-gas-pump"></i>
        <div data-i18n="Form Layouts">carburants</div>
      </a>
  </li>
  
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/kilometerges' ||  $_SERVER['PHP_SELF'] === '/kilometerges' ? 'active open' : ''?>">
      <a href="/kilometerges" class="menu-link ">
        <i class="menu-icon tf-icons bx bx-traffic-cone"></i>
        <div data-i18n="Form Layouts">kilometerage</div>
      </a>
    </li>
    <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/ordres' ||  $_SERVER['PHP_SELF'] === '/ordres' ? 'active open' : ''?>">
      <a href="/ordres" class="menu-link ">
        <i class="menu-icon tf-icons bx bx-task"></i>
        <div data-i18n="Form Layouts">Ordre de mission</div>
      </a>
     
    </li>
    <?php if($_SESSION['userRole'] === 'superAdmin'): ?>
      <li class="menu-header small text-uppercase"><span class="menu-header-text"></span></li>
      <li class="menu-item <?php echo $_SERVER['PHP_SELF'] === '/settings' ? 'active open' : ''?>">
        <a href="/settings" class="menu-link" <?php echo $_SERVER['PHP_SELF'] === '/settings' ? 'active open' : ''?>>
          <i class="menu-icon tf-icons bx bx-cog"></i>
          <div data-i18n="Website Settings">Website Settings</div>
        </a>
      </li>
    <?php endif ?>
    <?php endif ?>
  </ul>

</aside>
<!-- / Menu -->

    

    <!-- Layout container -->
    <div class="layout-page">
      
      



<!-- Navbar -->




<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
  

  

  

      
      

      
      
      <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0   d-xl-none ">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
          <i class="bx bx-menu bx-sm"></i>
        </a>
      </div>
      

      <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">

        


        
        <!-- Search -->
        <div class="navbar-nav align-items-center">
        </div>
        <!-- /Search -->
        

        <ul class="navbar-nav flex-row align-items-center ms-auto">
   

          <!-- User -->
          <li class="nav-item navbar-dropdown dropdown-user dropdown">
            <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
              <div class="avatar avatar-online">
                <img src="/uploads/users/<?php echo isset($loggedInUser['photo']) ? $loggedInUser['photo'] : '' ?>" alt class="w-px-40 h-px-40 rounded-circle">
              </div>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li>
                <a class="dropdown-item" href="/profile">
                  <div class="d-flex">
                    <div class="flex-shrink-0 me-3">
                      <div class="avatar avatar-online">
                        <img src="/uploads/users/<?php echo isset($loggedInUser['photo']) ? $loggedInUser['photo'] : '' ?>" alt class="w-px-40 h-px-40 rounded-circle">
                      </div>
                    </div>
                    <div class="flex-grow-1">
                      <span class="fw-semibold d-block"><?php echo isset($loggedInUser['fullName']) ? $loggedInUser['fullName'] : '' ?></span>
                      <small class="text-muted"><?php echo isset($loggedInUser['userRole']) ? $loggedInUser['userRole'] : '' ?></small>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <div class="dropdown-divider"></div>
              </li>
              <li>
                <a class="dropdown-item" href="/profile">
                  <i class="bx bx-user me-2"></i>
                  <span class="align-middle">My Profile</span>
                </a>
              </li>
             
              <li>
                <a class="dropdown-item" href="/logout">
                  <i class="bx bx-power-off me-2"></i>
                  <span class="align-middle">Log Out</span>
                </a>
              </li>
            </ul>
          </li>
          <!--/ User -->
          

        </ul>
      </div>

      
      
  </nav>
  

  
<!-- / Navbar -->

    