<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<!-- / Navbar -->

      <!-- Content wrapper -->
      <div class="content-wrapper">
        <!-- Content -->
          <div class="container-xxl flex-grow-1 container-p-y">     
<h4 class="fw-bold py-3 mb-4">
  <span class="text-muted fw-light">Ordres /</span> Ordres Details
</h4>
<form autocomplete="off" id="confirmerordre">
<div class="row">
  <div class="col-md-12">
    <div class="card p-5">
      <?php if(isset($_GET['s']) && $_GET['s'] === 'u'): ?>
        <span class="p-1" id="errDiv"><span style="color:green"> Ordre Mis à jour avec succés!</span></span>
      <?php else: ?>
        <span class="p-1" id="errDiv"></span>
      <?php endif ?>

      
        <script> var confirmation ='ticket' ;</script>
         <?php   
         $currentarray = $tickets;



if($ordre['data']['ligne']==='direct')

{for ($i = 0; $i < count($currentarray) - 1; $i++) {
    $minIndex = $i;
    for ($j = $i + 1; $j < count($currentarray); $j++) {
            if($currentarray[$j]['zone'] >$currentarray[$minIndex]['zone']){
                $minIndex=$minIndex;
            }
            if($currentarray[$j]['zone'] === $currentarray[$minIndex]['zone']){
                if ($currentarray[$j]['numero'] < $currentarray[$minIndex]['numero']) {
                    $minIndex = $j; 
                }
            }
      
    }
    if ($minIndex !== $i) {
        $tmp = $currentarray[$i];
        $currentarray[$i] = $currentarray[$minIndex];
        $currentarray[$minIndex] = $tmp;
    }
}}
else{for ($i = 0; $i < count($currentarray) - 1; $i++) {
    $maxIndex = $i;
    for ($j = $i + 1; $j < count($currentarray); $j++) {
        if ($currentarray[$j]['zone'] > $currentarray[$maxIndex]['zone']) {
            $maxIndex = $j; 
        } elseif ($currentarray[$j]['zone'] === $currentarray[$maxIndex]['zone']) {
            
            if ($currentarray[$j]['numero'] > $currentarray[$maxIndex]['numero']) {
                $maxIndex = $j; 
            }
        }
    }
    if ($maxIndex !== $i) {
        
        $tmp = $currentarray[$i];
        $currentarray[$i] = $currentarray[$maxIndex];
        $currentarray[$maxIndex] = $tmp;
    }
}

}

$heure = 0;

$heure = $ordre['data']['heure'];
foreach($currentarray as $ticket) :?>
          
          <?php if ($ticket['depart']===null): ?>
            <div class="mb-3">
            <label class="form-label" for="select_box2">excursion</label>
                <select class="form-control" id="select_box" aria-label="Default select example" required>
                    <option selected value="11"><?php echo $ordre['data']['nom'];?> </option>
                </select>
          </div>
          <div class="row">
            <div class="col mb-3">
              <label for="color" class="form-label">HEURE DE DEPART POUR : </br><strong> <?php echo $ticket['hotel'];?></strong> </label>
              <input type="time" id="<?php echo $ticket['numeroticket'] ?>" name="<?php echo $ticket['numeroticket'] ?>"value="<?php echo $heure;?>" class="form-control"  min="<?php echo $heure?>"placeholder="" required>        
            </div>
          </div>
          <div class="row g-2 mb-3">
            <div class="col mb-0" id="inputParent">
              <label for="phone-h" class="form-label">Nbr adulte</label>
              <input type="number" id="adulte" name="adulte" class="form-control" value="<?php echo $ticket['adulte'] ?>" placeholder="xxxxxxxxxx" required>
            </div>
            <div class="col mb-0" id="inputParent">
              <label for="phone-m" class="form-label">Nbr Enfant</label>
              <input type="number"  id="enfant" name="enfant" class="form-control" value="<?php echo $ticket['enfant'] ?>" placeholder="xxxxxxxxxx" required>
            </div>
            <div class="col mb-0" id="inputParent">
              <label for="phone-m" class="form-label">Nbr Bebe</label>
              <input type="number"  id="bebe" name="bebe" class="form-control" value="<?php echo $ticket['bebe'] ?>" placeholder="xxxxxxxxxx" required>
            </div>
          </div>
          <div class="row">
          <div class="mb-3">
          <label for="color" class="form-label"> tarifs pour un adulte  :<strong> <?php echo $ticket['tarifsadu']?> </strong></label>
          </br>
          <label for="color" class="form-label"> tarifs pour un enfant :  <strong> <?php echo $ticket['tarifsenf']?></strong></label>
          </br>
          <label for="color" class="form-label">  Montant total :<strong> <?php echo ($ticket['tarifsenf']*$ticket['enfant'] + $ticket['tarifsadu']*$ticket['adulte']) ?></strong></label>

          </div>

        </div>
          <div class="row">
          <div class="mb-3">
            <label class="form-label" for="paiment">paiment</label>
                <select class="form-control" id="paiment" aria-label="Default select example" required>
                <option value="<?php echo $ticket['etat']?>"><?php echo $ticket['etat']?></option>
                  <option value="payer">payer</option>
                  <option value="non">non payer</option>
                                </select>
          </div>
          
          </div>
          <script>

            var elementnumero = <?php echo $ticket['numeroticket']?>;
           var tarifsadu = <?php echo $ticket['tarifsadu']?>;
           var tarifsenf = <?php echo $ticket['tarifsenf']?>;

          </script>
          <div class="modal-bottom">
        <button type="submit" class="btn btn-primary">Confirmer Ticket</button>
      </div>
</br>
          
<?php break; ?>
<?php endif ?>

         
        <?php
         $heure=$ticket['depart'];
        
        endforeach
         ?>
   
   <?php 
$verifier = 1;
foreach ($currentarray as $ticket) {
    if ($ticket['depart'] === null) {
        $verifier = 0;
        break;
    }
}
?>
<?php if($verifier === 1): ?>
  <script> confirmation = 'ordre';</script>
  <div class="row">
      <div class="mb-3">
            <label class="form-label" for="select_box2">excursion</label>
                <select class="form-control" id="select_box" aria-label="Default select example" required>
                    <option selected value="11"><?php echo $ordre['data']['nom'];?> </option>
                </select>
          </div>
          
          <div class="mb-3">
            <label class="form-label" for="select_box">Vehicle</label>
                <select class="form-control" id="select_box2" aria-label="Default select example" required>
                    <option selected value="11" id=""><?php echo $ordre['data']['regisNumber'];?> </option>
                </select>
          </div>
          <div class="mb-3">
            <label class="form-label" for="select_box">chauffeur</label>
                <select class="form-control" id="select_box3" aria-label="Default select example" required>
                    <option selected value="11" id=""><?php echo $ordre['data']['driverFullName'];?></option>
                </select>
               </div>
       
          <div class="col mb-3">
          <label for="model" class="form-label">heure</label>
          <input type="time" name="heure" id="model" value="<?php echo $ordre['data']['heure'];?>" class="form-control" placeholder="">
        </div>
      </div>

      <div class="row">
        <div class="col mb-3">
          <label for="color" class="form-label">Excursion Destination</label>
          <input type="text" name="excursion" id="color" value="<?php echo $ordre['data']['nom'];?>" class="form-control" placeholder="">
        </div>
      </div>
      <div class="row">
            <div class="col mb-3">
              <label for="color" class="form-label">Agence</label>
              <input type="text" id="agence" name="agence"value="<?php echo $ordre['data']['agence'];?>" class="form-control" placeholder="" required>
            </div>
          </div>
        <div class="modal-midlle">
            <button type="submit" class="btn btn-primary">Confirmer Ordre</button>
        </div>
    </form>
<?php endif; ?>
    </div>

      
    </div>
  </div>
</div>


            
          </div>
          <!-- / Content -->

          
          

<!-- Footer -->
<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <script src="/views/api/ordm.API.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>

  <!-- Page JS -->
  <script src="/views/assets/js/pages-account-settings-account.js"></script>
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/pages-account-settings-account.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:07 GMT -->
</html>
