<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin' && $_SESSION['userRole']!== 'chauffeur'&& $_SESSION['userRole'] !== 'Agent'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<style>
    input:focus:required:invalid {border: 1px solid red;}
    input:required:valid { border: 1px solid #d9dee3; }
    select:focus:required:invalid {border: 1px solid red;}
    select:required:valid { border: 1px solid #d9dee3; }
    textarea:focus:required:invalid {border: 1px solid red;}
    textarea:required:valid { border: 1px solid #d9dee3; }
</style>
<link rel="stylesheet" href="/views/assets/css/selectize.css"/>
      

      <!-- Content wrapper -->
      <div class="content-wrapper">

        <!-- Content -->
        
          <div class="container-xxl flex-grow-1 container-p-y">
            
            


<!-- Basic Layout -->
<div class="row">
  <div class="col-xl">
    <div class="card mb-4">
   
      <div class="card-body">
      <ul class="nav nav-pills flex-column flex-md-row mb-3">
    
    <li class="nav-item"><a class="nav-link " href="/ordres"> Toutes les ordres</a>
  
   
  </li>
    <li class="nav-item"><a class="nav-link  " href="/mission"> Nouvelle Mission</a></li>
    <li class="nav-item"><a class="nav-link active" href="/ordre">Nouvelle Excursion/Transferet</a></li>

  </ul>
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Ordres/</span> Ajouter Odre Excursion/Transferet</h4>
    
        <span id="addordreErr"></span>
        <form autocomplete="off" id="addOrdreForm">

        <div class="mb-3">
            <label class="form-label" for="select_box2">type</label>
                <select class="form-control" id="select_box" aria-label="Default select example" required>
                    <option selected value="">excursion / transferet </option>
                </select>
          </div>
          

          <div class="mb-3">
            <label class="form-label" for="select_box">Vehicule</label>
                <select class="form-control" id="select_box2" aria-label="Default select example" required>
                    <option selected value="" id="">Vehicle </option>
                </select>
          </div>
          <?php if($_SESSION['userRole'] === 'superAdmin' ||$_SESSION['userRole'] === 'Admin'||$_SESSION['userRole'] === 'Agent' ): ?>
          <div class="mb-3">
            <label class="form-label" for="select_box3">Chauffeur</label>
                <select class="form-control" id="select_box3" aria-label="Default select example" required>
                    <option selected value="" id="">Chauffeur </option>
                </select>
          </div>
          <?php endif ?>
          <?php if($_SESSION['userRole'] === 'chauffeur' ): ?>
          <div class="mb-3" id="select_box3" value="0">
          </div>
          <?php endif ?>
          <div class="row">
            <div class="col mb-3"> 
              <label for="color" class="form-label">date excursion</label>
              <input type="date" id="excursion" name="excursion"class="form-control"oninvalid="this.setCustomValidity('')" placeholder="" required min="<?php echo date('Y-m-d'); ?>" value="<?php echo date('Y-m-d'); ?>">
            </div>
          </div> 
          <div class="row">
            <div class="col mb-3">
              <label for="color" class="form-label">Heure</label>
              <input type="time"  name="heure" id="heure" class="form-control" placeholder="" required>
            </div>
          </div>
          <div class="row">
            <div class="col mb-3"> 
              <label for="color" class="form-label">date de retour</label>
              <input type="date" id="dater" name="dater" oninput="validatedate()"  class="form-control" placeholder="" required min="<?php echo date('Y-m-d'); ?>" value="<?php echo date('Y-m-d'); ?>">
            </div>
          </div> 
          <div class="row">
            <div class="col mb-3">
              <label for="color" class="form-label">Heure de retour</label>
              <input type="time"  name="heurer" id="heurer" class="form-control" placeholder="" required>
            </div>
          </div>
          <div class="row">
            <div class="col mb-3">
              <label for="color" class="form-label">Agence</label>
              <input type="text" id="agence" name="agence" class="form-control" placeholder="" required>
            </div>
          </div>

          <button type="submit" class="btn btn-primary">Ajouter</button>
        </form>
      </div>
    </div>
  </div>
</div>

            
          </div>
          <!-- / Content -->

          
          

<!-- Footer -->
  <?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  

  



  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>
    <script src="/views/api/ordm.API.js"></script>
  <script src="/views/dselect.js"></script>

  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/form-layouts-vertical.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:29 GMT -->
</html>
