<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<style>
    input:focus:required:invalid {border: 1px solid red;}
    input:required:valid { border: 1px solid #d9dee3; }
    select:focus:required:invalid {border: 1px solid red;}
    select:required:valid { border: 1px solid #d9dee3; }
    textarea:focus:required:invalid {border: 1px solid red;}
    textarea:required:valid { border: 1px solid #d9dee3; }
</style>
      <!-- Content wrapper -->
      <div class="content-wrapper">
        <!-- Content -->
          <div class="container-xxl flex-grow-1 container-p-y">
            
                  
          <h4 class="fw-bold py-3 mb-4">
            <span class="text-muted fw-light">Utilisateurs /</span> Chauffeurs
          </h4>

          <!-- Basic Bootstrap Table -->
          <div class="card">
            <div class="flexDiv">
              <h5 class="card-header">Toutes les Chauffeurs</h5>
              <!-- Button trigger modal -->
              <form id="searchDriverForm" autocomplete="off">
                <div class="d-flex g-3">
                    <input name="searchDriver" class="form-control form-control-sm me-2" type="search" placeholder="Search for driver">
                    <button type="submit" disabled="true" id="searchDriverBtn" class="btn btn-primary btn-sm">Search</button>
                </div>
              </form>
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalScrollable">
                Ajouter Chauffeur
              </button>
            </div>
          
            <div class="table-responsive text-nowrap">
            <table class="table">
                <thead>
                  <tr>
                    <th>Nom</th>
                    <th>Chauffeur Num</th>
                    <th>Email</th>
                    <th>telephone</th>
                 
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody class="table-border-bottom-0"></tbody>
              </table>
              
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <div class="demo-inline-spacing">
                    <!-- Basic Pagination -->
                    <nav aria-label="Page navigation">
                      <ul class="pagination">
                       
                      </ul>
                    </nav>
                    <!--/ Basic Pagination -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--/ Basic Bootstrap Table -->
          <div class="modal fade" id="modalScrollable2" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalScrollableTitle">Chauffeur Details</h5><br />
                </div>
                  <span class="ms-4 me-4" id="genPass"></span>
                <div class="modal-body" id="detailsBody">
                  <div class="text-center fs-3">
                    <i class='bx bx-loader-alt bx-spin fs-1'></i>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" id="closeDetails" data-bs-dismiss="modal">fermer</button>
                  <span id="genPassBtnDiv"></span>
                </div>
              </div>
            </div>
          </div>
          <hr class="my-5">
                    
      </div>
<!-- / Content -->
 <!-- Default Modal -->
 <div class="col-lg-8 col-md-8">
  <div class="modal fade " id="modalScrollable" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog  modal-lg modal-dialog-scrollable" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalScrollableTitle">Ajouter Chauffeur</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="p-3" id="successDiv"></div>
        <div class="modal-body">
      <form autocomplete="off" id="addDriver">
          <div class="card-body">
          <div class="row">
            <div class="col mb-3" id="inputParent">
              <label for="nameBasic" class="form-label">Nom</label>
              <input type="text" id="nameBasic" name="driverName" class="form-control" placeholder="Enter Name" required>
            </div>
          </div>

          <div class="row">
            <div class="col mb-3" id="inputParent">
              <label for="dob" class="form-label">Date de naissance</label>
              <input type="date" name="dob" id="dob" class="form-control" placeholder="Driver's Date of Birth" required>
            </div>
          </div>

          <div class="row g-2 mb-3">
            <div class="col mb-0" id="inputParent">
              <label for="phone-h" class="form-label">Telehone (maison)</label>
              <input type="number" min="7" name="phoneOne" id="phone-h" class="form-control" placeholder="xxxxxxxxxx" required>
            </div>
            <div class="col mb-0" id="inputParent">
              <label for="phone-m" class="form-label">Telephone (mobile)</label>
              <input type="number" min="7" name="phoneTwo" id="phone-m" class="form-control" placeholder="xxxxxxxxxx" required>
            </div>
          </div>

          <div class="row g-2 mb-3">
            <div class="col mb-0" id="inputParent">
              <label for="id-number" class="form-label">Cin</label>
              <input type="text" name="idNumber" id="id-number" min="7"class="form-control" placeholder="xxxxxxxxxx" required>
            </div>
            <div class="col mb-0" id="inputParent">
              <label for="email" class="form-label">Email</label>
              <input type="email" name="driverEmail" id="email" class="form-control" placeholder="xxx@xxxx.xxx" required>
            </div>
          </div>
          
        </div>
        <div class="modal-footer">
          <button type="button" id="canDriverBtn" class="btn btn-outline-secondary" data-bs-dismiss="modal">fermer</button>
          <button type="submit" id="addDriverBtn" class="btn btn-primary">sauvgarder changament</button>
        </div>
      </form>
      </div>
    </div>
  </div>
</div>




<!-- Footer -->
  <?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
      <div class="content-backdrop fade"></div>
    </div>
    <!-- Content wrapper -->
  </div>
  <!-- / Layout page -->
</div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->
  <script src="/views/api/drivers.API.js"></script>
 
  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <script src="/views/assets/js/pages-account-settings-account.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>

  <!-- Page JS -->
  
  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/tables-basic.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:32 GMT -->
</html>
