<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
  
<!-- / Navbar -->

      

      <!-- Content wrapper -->
      <div class="content-wrapper">

        <!-- Content -->
        
          <div class="container-xxl flex-grow-1 container-p-y">
            
            
<h4 class="fw-bold py-3 mb-4">
  <span class="text-muted fw-light">Employes /</span> Employe Details
</h4>

    <div class="row">
    <div class="col-md-12">
       
        <div class="card mb-4 p-5">
        <h5 class="card-header">Profile Details</h5>
          <p style="margin-left: 30px" class="p-2" id="pError"></p>
        <!-- Account -->
        <form autocomplete="off" id="updateWorkerFrom" enctype="multipart/form-data">
          
              
            
            <div class="row">
              <div class="col mb-3" id="inputParent">
                <label for="nameBasic" class="form-label">Nom</label>
                <input type="text" id="nameBasic" value="<?php echo $worker['data']['fullName']; ?>" name="workerName" class="form-control" placeholder="Enter Name" required>
                 <small></small>
              </div>
            </div>

            <div class="row">
              <div class="col mb-3" id="inputParent">
                <label for="dob" class="form-label">Date de naissance</label>
                <input type="date" id="dob" name="dob" value="<?php echo $worker['data']['bateOfBirth'] ?>" class="form-control" placeholder="Worker's Date of Birth" required>
                 <small></small>
              </div>
            </div>

            <div class="row">
              <div class="col mb-3" id="selectParent">
                <label for="workerRoles" class="form-label" id="workerRoles">Employe Role</label>
                <select  name="workerRole" id="workerRole"class="form-select" required>
                  <option value="">select</option>
                  <option  value="agent">agent</option>
                  <option value="admin">Admin</option>
                </select>
                 <small></small>
              </div>
            </div>

            <div class="row g-2 mb-3">
              <div class="col mb-0" id="inputParent">
                <label for="phone-h" class="form-label">Portable</label>
                <input type="number" name="workerPhone1" value="<?php echo $worker['data']['phoneOne']; ?>" id="phone-h" class="form-control" placeholder="xxxxxxxxxx" required>
                 <small></small>
              </div>
              <div class="col mb-0" id="inputParent">
                <label for="phone-m" class="form-label">Telephone</label>
                <input type="number" name="workerPhone2" id="phone-m" value="<?php echo $worker['data']['phoneTwo']; ?>" class="form-control" placeholder="xxxxxxxxxx" required>
                 <small></small>
              </div>
            </div>

            <div class="row g-2 mb-3">
              <div class="col mb-0" id="inputParent">
                <label for="id-number" class="form-label">Cin</label>
                <input type="text" name="workerId" id="id-number" value="<?php echo $worker['data']['idNumber']; ?>" class="form-control" placeholder="xxxxxxxxxx" required>
                 <small></small>
              </div>
              <div class="col mb-0" id="inputParent">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="workerEmail" value="<?php echo $worker['data']['userEmail']; ?>" id="email" class="form-control" placeholder="xxx@xxxx.xxx" required>
                 <small></small>
              </div>
            </div>

            
            
            <div class="modal-footer">
              <button type="submit" id="addWorkerBtn" class="btn btn-primary">Sauvgarder changament</button>
            </div>
          </div>
        </div>
        <!-- /Account -->
        </div>
        </form>
    </div>
    </div>
   
    <script src="/views/newWorker.js"></script>
    <script src="/views/api/workers.API.js"></script>


          <!-- / Content -->

          
          

<!-- Footer -->
<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>

  <!-- Page JS -->
  <script src="/views/assets/js/pages-account-settings-account.js"></script>
  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/pages-account-settings-account.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:07 GMT -->
</html>
