<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<style>
    input:focus:required:invalid {border: 1px solid red;}
    input:required:valid { border: 1px solid #d9dee3; }
    select:focus:required:invalid {border: 1px solid red;}
    select:required:valid { border: 1px solid #d9dee3; }
    textarea:focus:required:invalid {border: 1px solid red;}
    textarea:required:valid { border: 1px solid #d9dee3; }
</style>
  
<!-- / Navbar -->

      

      <!-- Content wrapper -->
      <div class="content-wrapper">

        <!-- Content -->
        
          <div class="container-xxl flex-grow-1 container-p-y">
            
            
<h4 class="fw-bold py-3 mb-4">
  <span class="text-muted fw-light">Formlaire /</span>Details
</h4>

<div class="row">
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-body">
      <form  autocomplete="off" id="userDetailsForm">
          <span id="settingsErr"></span>
           
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="basic-default-name">Nom</label>
            <div class="col-sm-10">
              <input type="text" name="fullName" class="form-control" value="<?php echo $loggedInUser['fullName'] ? $loggedInUser['fullName'] : ''?>" id="basic-default-name" placeholder="" required/>
            </div>
          </div>
          
          <div class="row justify-content-end">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Sauvgarder</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card mb-4">
      <h5 class="card-header">Changement mot de passe</h5>
      <div class="card-body">
        <form autocomplete="off" id="passwordForm">
          <span id="settingsErr"></span>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="curPass">Mot de passe ancien</label>
                <div class="col-sm-10">
                <input type="password"  oninvalid="this.setCustomValidity(`Current Password shouldn't be empty!`)" oninput="this.setCustomValidity('')" name="curPass" class="form-control" placeholder="" required/>
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="newPass">Nouvelle mot de passe</label>
                <div class="col-sm-10">
                <input type="password"  oninvalid="this.setCustomValidity(`New Password shouldn't be empty!`)" oninput="this.setCustomValidity('')" name="newPass" class="form-control" id="newPass" placeholder="" required/>
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="conPass">confirmation mot de passe<</label>
                <div class="col-sm-10">
                <input type="password"  oninvalid="this.setCustomValidity(`Confirm Password shouldn't be empty!`)" oninput="this.setCustomValidity('')" name="conPass" class="form-control" id="conPass" placeholder="" required/>
                </div>
            </div>
            <div class="row justify-content-end">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Changement Mot de passe</button>
                </div>
            </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Form controls -->
  
  <!-- Input Sizing -->
  

  <!-- Default Checkboxes and radios & Default checkboxes and radios -->
  

  

    <!-- File input -->
    
  </div>
</div>

            
          </div>
          <!-- / Content -->

          
          

<!-- Footer -->
<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  
  

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/api/profile.API.js"></script>
  <script src="/views/assets/vendor/js/menu.js"></script>

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>
  <script src="/views/assets/js/pages-account-settings-account.js"></script>

  <!-- Page JS -->
  
  
  
</body>


</html>
