<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<!-- / Navbar -->

      

      <!-- Content wrapper -->
      <div class="content-wrapper">

        <!-- Content -->
        
          <div class="container-xxl flex-grow-1 container-p-y">
            
            
<h4 class="fw-bold py-3 mb-4">
  <span class="text-muted fw-light">Vehicules /</span> Vehicle Details
</h4>
<form autocomplete="off" id="addmain">


<div class="row">
  <div class="col-md-12">
    <div class="card p-5">
      <?php if(isset($_GET['s']) && $_GET['s'] === 'u'): ?>
        <span class="p-1" id="errDiv"><span style="color:green"> Vehicule Mis à jour avec succès!</span></span>
      <?php else: ?>
        <span class="p-1" id="errDiv"></span>
      <?php endif ?>
      
      <div class="row">
              <div class="col mb-3" id="selectParent">
                <label for="model" class="form-label">model de vehicle</label>
                <select id="vehicle" name="vehicle" class="form-select" required>
                  <option value="<?php echo $vehicle['data']['vehicleUuid'];?>"><?php echo $vehicle['data']['model'];?></option>
                 
                 </select>
                 </div>
                 </div>
                 <div class="row">
              <div class="col mb-3" id="selectParent">
                <label for="model" class="form-label">nUMERO DE matricel</label>
                <select id="model" name="model" class="form-select" required>
                  <option value="<?php echo $vehicle['data']['regisNumber'];?>"><?php echo $vehicle['data']['regisNumber'];?></option>
                 
                 </select>
                 </div>
                 </div>
                 <div class="row">
              <div class="col mb-3" id="selectParent">
                <label for="model" class="form-label">VEHICULE COULEUR</label>
                <select id="models" name="models" class="form-select" required>
                  <option value="<?php echo $vehicle['data']['color'];?>" ><?php echo $vehicle['data']['color'];?> </option>
                 
                 </select>
                 </div>
                 </div>
                 <div class="row">
            <div class="col mb-3"> 
              <label for="dateen" class="form-label">date entre a l'entretien</label>
              <input type="date" id="dateen" name="dateen"class="form-control"oninvalid="this.setCustomValidity('')" placeholder="" required min="" value="<?php echo date('Y-m-d'); ?>">
            </div>
          </div> 
          <div class="row">
            <div class="col mb-3"> 
              <label for="color" class="form-label">date sortir de l'entretien</label>
              <input type="date" id="datesor" name="datesor"class="form-control"oninvalid="this.setCustomValidity('')" placeholder="" required min="" value="<?php echo date('Y-m-d'); ?>">
            </div>
          </div> 
          <div class="row">
          <div class="mb-3">
            <label class="form-label" for="basic-default-fullname">total montant </label>
            <input name="total" id="total" value="" type="number" step="0.01" class="form-control" oninput="this.setCustomValidity('')" id="basic-default-fullname" placeholder="" required/>
          </div>
      
          </div>
          <div class="row">
  <div class="mb-3">
    <label class="form-label" for="type">Type de maintenance</label>
    <select class="form-control" id="type" aria-label="Default select example" required>
      <option value="" selected disabled>Choisissez le type de maintenance</option>
      <option value="preventive">Maintenance préventive</option>
      <option value="corrective">Maintenance corrective</option>
      <option value="predictive">Maintenance prédictive</option>
      <option value="emergency">Maintenance d'urgence</option>
    </select>
  </div>
</div>
          <div class="row">
          <div class="mb-3">
            <label class="form-label" for="basic-default-fullname">Obeservation</label>
            <input name="obeservation" id="obeservation" value="" type="text" class="form-control" oninput="this.setCustomValidity('')" id="basic-default-fullname" placeholder="" required/>
          </div>
          </div>
      
                
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Modifier Vehicule</button>
      </div>
    </div>

      
    </div>
  </div>
</div>
</form>

            
          </div>
          <!-- / Content -->

          
          

<!-- Footer -->
<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>
  <!-- / Layout wrapper -->

  

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <script src="/views/api/maintenance.API.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>

  <!-- Page JS -->
  <script src="/views/assets/js/pages-account-settings-account.js"></script>
  
  
</body>


<!-- Mirrored from demos.themeselection.com/sneat-bootstrap-html-admin-template-free/html/pages-account-settings-account.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 26 Dec 2022 09:09:07 GMT -->
</html>
