<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'&& $_SESSION['userRole'] !== 'Agent'):
  include  $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
 include  $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>
<style>
    input:focus:required:invalid {border: 1px solid red;}
    input:required:valid { border: 1px solid #d9dee3; }
    select:focus:required:invalid {border: 1px solid red;}
    select:required:valid { border: 1px solid #d9dee3; }
    textarea:focus:required:invalid {border: 1px solid red;}
    textarea:required:valid { border: 1px solid #d9dee3; }
</style>
<!-- / Navbar -->

      <!-- Content wrapper -->
      <div class="content-wrapper">
        <!-- Content -->
          <div class="container-xxl flex-grow-1 container-p-y">
            
                  
          <h4 class="fw-bold py-3 mb-4">
            <span class="text-muted fw-light">Users /</span> Mission
          </h4>

          <!-- Basic Bootstrap Table -->
          <div class="card">
            <div class="flexDiv">
              <h5 class="card-header">Toutes les Missions</h5>
              <!-- Button trigger modal -->
              <form id="searchDriverForm" autocomplete="off">
                <div class="d-flex g-3">
                    <input name="searchexcursion" class="form-control form-control-sm me-2" type="search" placeholder="Recherche une excursion">
                    <button type="submit" disabled="true" id="searchexcursionBtn" class="btn btn-primary btn-sm">Rechercher</button>
                </div>
              </form>
            </div>
            <span class="ms-3" id="deleteErr"></span>
            <div class="table-responsive text-nowrap">
              <table class="table">
                <thead>
                  <tr>
                    <th>Type</th>
                    <th>Nom </th>
                    <th>Destination</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody class="table-border-bottom-0"></tbody>
              </table>
              
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <div class="demo-inline-spacing">
                    <!-- Basic Pagination -->
                    <nav aria-label="Page navigation">
                      <ul class="pagination"></ul>
                    </nav>
                    <!--/ Basic Pagination -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--/ Basic Bootstrap Table -->
          <div class="modal fade" id="modalScrollable2" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable" role="document">
              <div class="modal-content">
                <div class="modal-header">
                <canvas id="detailsBody2" width="50" height="20"></canvas>
                  <h5 class="modal-title" id="modalScrollableTitle">Statistique kilometerage par mois </h5>
                </div>
             
                  <div class="text-center fs-3">
                  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                  <canvas id="detailsBody" width="50" height="20"></canvas>
              
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" id="closeDetails" data-bs-dismiss="modal">Fermer</button>
                </div>
              </div>
            </div>
          </div>
          <hr class="my-5">
                    
      </div>
<!-- / Content -->
 <!-- Default Modal -->





<!-- Footer -->
<?php include  $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
<!-- / Footer -->

          
      <div class="content-backdrop fade"></div>
    </div>
    <!-- Content wrapper -->
  </div>
  <!-- / Layout page -->
</div>

    
    
    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
    
    
  </div>

  <!-- Core JS -->
  <!-- build:js assets/vendor/js/core.js -->
  <script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
  <script src="/views/assets/vendor/libs/popper/popper.js"></script>
  <script src="/views/assets/vendor/js/bootstrap.js"></script>
  <script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
  <script src="/views/assets/vendor/js/menu.js"></script>
  <script src="/views/assets/js/pages-account-settings-account.js"></script>
  <script src="/views/api/statistique.API.js"></script>
  <!-- endbuild -->

  <!-- Vendors JS -->
  
  

  <!-- Main JS -->
  <script src="/views/assets/js/main.js"></script>

  <!-- Page JS -->
  
</body>


</html>
